name: Deploy Jekyll to Specific Subdomains

on:
  push:
    branches:
      - '*'  # Trigger on all branches

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby and Jekyll
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'  # Adjust to your Jekyll version requirements

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build the Jekyll site
      run: |
        bundle exec jekyll build  # Builds the site into the `_site` directory

    - name: Create CNAME file for subdomain
      run: |
        case "${GITHUB_REF#refs/heads/}" in
          "main")
            echo "john-ogletree.com" > _site/CNAME
            ;;
          "about")
            echo "about.john-ogletree.com" > _site/CNAME
            ;;
          "services")
            echo "services.john-ogletree.com" > _site/CNAME
            ;;
          "services-designandprint")
            echo "services-designandprint.john-ogletree.com" > _site/CNAME
            ;;
          "services-digitalmedia")
            echo "services-digitalmedia.john-ogletree.com" > _site/CNAME
            ;;
          "services-videoandanimation")
            echo "services-videoandanimation.john-ogletree.com" > _site/CNAME
            ;;
          "services-audio")
            echo "services-audio.john-ogletree.com" > _site/CNAME
            ;;
          "pricing-designandprint")
            echo "pricing-designandprint.john-ogletree.com" > _site/CNAME
            ;;
          "pricing-digitalmedia")
            echo "pricing-digitalmedia.john-ogletree.com" > _site/CNAME
            ;;
          "pricing-videoandanimation")
            echo "pricing-videoandanimation.john-ogletree.com" > _site/CNAME
            ;;
          "pricing-audio")
            echo "pricing-audio.john-ogletree.com" > _site/CNAME
            ;;
          "projects")
            echo "projects.john-ogletree.com" > _site/CNAME
            ;;
          "projects-graphics")
            echo "projects-graphics.john-ogletree.com" > _site/CNAME
            ;;
          "projects-graphics-logoverse")
            echo "projects-graphics-logoverse.john-ogletree.com" > _site/CNAME
            ;;
          "projects-graphics-visionunveiled")
            echo "projects-graphics-visionunveiled.john-ogletree.com" > _site/CNAME
            ;;
          "projects-videos")
            echo "projects-videos.john-ogletree.com" > _site/CNAME
            ;;
          "projects-music")
            echo "projects-music.john-ogletree.com" > _site/CNAME
            ;;
          "projects-books")
            echo "projects-books.john-ogletree.com" > _site/CNAME
            ;;
          "projects-books-insidethestorm")
            echo "projects-books-insidethestorm.john-ogletree.com" > _site/CNAME
            ;;
          "resume")
            echo "resume.john-ogletree.com" > _site/CNAME
            ;;
          "contact")
            echo "contact.john-ogletree.com" > _site/CNAME
            ;;
          "directory")
            echo "directory.john-ogletree.com" > _site/CNAME
            ;;
          *)
            echo "No CNAME defined for this branch" > _site/CNAME
            ;;
        esac

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.DEPLOY_KEY }}  # Add your SSH deploy key in GitHub Secrets
        publish_dir: ./_site  # The directory where Jekyll builds the site
        user_name: "github-actions"
        user_email: "github-actions@github.com"
        branch: gh-pages  # Deploy to the gh-pages branch
        cname: "$(cat _site/CNAME)"  # Dynamically set the CNAME based on the branch

    - name: Clean up
      run: rm -f _site/CNAME
